# Generated by Django 4.0.1 on 2022-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.CharField(choices=[('title', 'title'), ('urgency', 'urgency'), ('user', 'user'), ('due_date', 'due_date')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('no priority', '0'), ('high priority', '3'), ('low priority', '1'), ('medium priority', '2')], default='0', max_length=20),
        ),
    ]
