# Generated by Django 4.0.1 on 2022-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_order_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('urgency', 'urgency'), ('title', 'title'), ('user', 'user'), ('due_date', 'due_date')], default='due_date', max_length=10),
        ),
    ]
