# Generated by Django 4.0.1 on 2022-01-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_order_group_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('user', 'user'), ('due_date', 'due_date'), ('title', 'title'), ('urgency', 'urgency')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('no priority', '0'), ('low priority', '1'), ('high priority', '3'), ('medium priority', '2')], default='0', max_length=20),
        ),
    ]
