# Generated by Django 4.0.1 on 2022-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_content_task_description_alter_group_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('urgency', 'urgency'), ('user', 'user'), ('due_date', 'due_date'), ('title', 'title')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='27-01-2022'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('no priority', '0'), ('low priority', '1'), ('medium priority', '2'), ('high priority', '3')], default='0', max_length=20),
        ),
    ]
