# Generated by Django 4.0.1 on 2022-01-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_group_order_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('title', 'title'), ('user', 'user'), ('due_date', 'due_date'), ('urgency', 'urgency')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low priority', '1'), ('no priority', '0'), ('medium priority', '2'), ('high priority', '3')], default='0', max_length=20),
        ),
    ]
