# Generated by Django 4.0.1 on 2022-01-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_group_order_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('title', 'title'), ('urgency', 'urgency'), ('user', 'user'), ('due_date', 'due_date')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high priority', '3'), ('medium priority', '2'), ('low priority', '1'), ('no priority', '0')], default='0', max_length=20),
        ),
    ]
