# Generated by Django 4.0.1 on 2022-01-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_group_order_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('urgency', 'urgency'), ('due_date', 'due_date'), ('user', 'user'), ('title', 'title')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('no priority', '0'), ('low priority', '1'), ('high priority', '3'), ('medium priority', '2')], default='0', max_length=20),
        ),
    ]
