# Generated by Django 4.0.1 on 2022-01-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_group_order_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(choices=[('title', 'title'), ('due_date', 'due_date'), ('urgency', 'urgency'), ('user', 'user')], default='due_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high priority', '3'), ('low priority', '1'), ('medium priority', '2'), ('no priority', '0')], default='0', max_length=20),
        ),
    ]
