# Generated by Django 4.0.1 on 2022-01-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_group_order_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('no priority', '0'), ('medium priority', '2'), ('low priority', '1'), ('high priority', '3')], default='0', max_length=20),
        ),
    ]
