# Generated by Django 4.0.1 on 2022-01-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.group'),
        ),
    ]
