# Generated by Django 4.0.1 on 2022-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_task_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(default='due_date/asc', max_length=10),
        ),
    ]
