# Generated by Django 4.0.1 on 2022-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.CharField(default='due_date/asc', max_length=15),
        ),
    ]
